window.PORTFOLIO_DATA = {
  artist: {
    nameZh: "杨晨欣",
    nameEn: "Yang Chenxin",
    email: "2538219086@qq.com",
  },
  works: [
    {
      id: "work-introduction",
      order: 1,
      featured: true,
      titleZh: "作品简介",
      titleEn: "The Critic",
      aliases: ["The Critic"],
      year: "2026",
      categoryZh: "观念装置",
      categoryEn: "Conceptual Installation",
      roleZh: "个人作品 / 后续项目",
      roleEn: "Personal Work / Project Development",
      preview: {
        type: "image",
        src: "assets/images/the-critic.jpg",
        alt: "观众在公共空间观看《作品简介》装置",
        orientation: "portrait",
      },
      gallery: [
        { type: "image", src: "assets/images/gallery/critic-02.jpg", alt: "《作品简介》装置现场图二", orientation: "landscape" },
        { type: "image", src: "assets/images/gallery/critic-03.jpg", alt: "观众使用《作品简介》实物装置", orientation: "landscape" },
        { type: "image", src: "assets/images/gallery/critic-physical/critic-physical-02.jpg", alt: "《作品简介》长纸带实物装置现场", orientation: "landscape" },
        { type: "image", src: "assets/images/gallery/critic-physical/critic-physical-01.jpg", alt: "《作品简介》打印纸带与装置细节", orientation: "landscape" },
        { type: "image", src: "assets/images/gallery/critic-physical/critic-physical-03.jpg", alt: "The Critic 在林茨电子艺术节中的 Le Creative 展示效果一", orientation: "landscape" },
        { type: "image", src: "assets/images/gallery/critic-physical/critic-physical-04.jpg", alt: "The Critic 在林茨电子艺术节中的 Le Creative 展示效果二", orientation: "landscape" },
        { type: "image", src: "assets/images/gallery/critic-physical/critic-physical-05.jpg", alt: "The Critic 在林茨电子艺术节中的 Le Creative 展示效果三", orientation: "landscape" },
      ],
      transition: "aperture",
      summaryZh:
        "作品关注两个问题：观众对阐释的依赖，以及文字如何在展览中获得权威。面对难以理解的艺术作品，我们常借助展签和文字说明建立理解；当文字出现在美术馆或展览中，它也自然获得可信度并影响观看。《The Critic》将持续实时更新的 AI 生成文本置于真实作品旁，形成看似专业的平行解释。作品进一步追问：当解释越来越容易获得，我们是否也在逐渐依赖这些文本，并让渡自己的观看、感受与解释权？",
      summaryEn:
        "The work focuses on two questions: our dependence on interpretation, and how text gains authority in exhibitions. When an artwork is difficult to understand, we often rely on labels and written explanations. Within museums and exhibitions, these texts naturally acquire credibility and shape the way we see. The Critic places continuously updated AI-generated texts beside real artworks, creating seemingly professional parallel interpretations. It asks whether, as interpretations become easier to obtain, we are becoming dependent on them and giving away our own ways of seeing, feeling and interpreting.",
      stages: [
        {
          year: "2026",
          labelZh: "前期作品",
          labelEn: "Initial Work",
          title: "《作品简介》",
          detailZh: "以观念装置的形式建立作品主体，并提出关于 AI、艺术生产与艺术身份的核心问题。",
          detailEn: "The initial installation establishes the work and its questions around AI, artistic production and authorship.",
        },
        {
          year: "2026",
          labelZh: "后续项目",
          labelEn: "Later Project",
          title: "The Critic · 林茨电子艺术节",
          detailZh: "作品进入展览制度内部：艺术家的主观观察先被压缩为语言碎片，再由 AI 补全为具有不同可信程度的文本，讨论艺术意义如何被语言、位置与制度共同认证。",
          detailEn: "The work enters the exhibition system: the artist's subjective observations are compressed into fragments, then expanded by AI into texts with different degrees of credibility, asking how meaning is certified through language, position and institutions.",
        },
      ],
      futureAssets: [],
    },
    {
      id: "revelation",
      order: 2,
      featured: true,
      homepageMedia: "images",
      titleZh: "启示录",
      titleEn: "Revelation",
      aliases: [],
      year: "2025",
      categoryZh: "动态装置",
      categoryEn: "Kinetic Installation",
      roleZh: "团队作品",
      roleEn: "Collaborative Work",
      preview: {
        type: "image",
        src: "assets/images/revelation.jpg",
        alt: "《启示录》动态装置在黑色展览空间中的现场",
        orientation: "portrait",
      },
      gallery: [
        { type: "video", src: "assets/video/revelation-web.mp4", poster: "assets/images/revelation.jpg", alt: "《启示录》动态装置完整影像", orientation: "landscape" },
        { type: "image", src: "assets/images/gallery/revelation-02.jpg", alt: "《启示录》装置内部结构与光影", orientation: "portrait" },
        { type: "image", src: "assets/images/gallery/revelation-03.jpg", alt: "《启示录》装置侧面现场", orientation: "landscape" },
      ],
      transition: "vertical",
      summaryZh:
        "某一天，人类发现了一种会拟态成自然元素的生物。它们被捕捉、集中观察，在视线之外竭力挣脱。作品把观察、控制与自由放在同一个运动结构中。",
      summaryEn:
        "A newly discovered life form mimics elements of nature and is captured for observation. Beyond the observer's gaze, it struggles to escape. The work places observation, control and freedom within one moving structure.",
      stages: [],
      futureAssets: [],
    },
    {
      id: "body-massage-dj",
      order: 3,
      featured: true,
      homepageMedia: "images",
      titleZh: "人体按摩打碟机",
      titleEn: "Body Massage DJ Machine",
      aliases: ["如果我是 DJ 你会爱我吗"],
      year: "2025",
      categoryZh: "互动声音装置",
      categoryEn: "Interactive Sound Installation",
      roleZh: "团队作品",
      roleEn: "Collaborative Work",
      preview: {
        type: "image",
        src: "assets/images/body-massage-dj.jpg",
        alt: "《人体按摩打碟机》后续项目中的反光装置细节",
        orientation: "landscape",
      },
      gallery: [
        { type: "image", src: "assets/images/gallery/body-dj-02.jpg", alt: "《人体按摩打碟机》项目现场图二", orientation: "portrait" },
        { type: "image", src: "assets/images/gallery/body-dj-03.jpg", alt: "《人体按摩打碟机》项目现场图三", orientation: "landscape" },
        { type: "image", src: "assets/images/gallery/body-dj-04.jpg", alt: "《人体按摩打碟机》项目现场图四", orientation: "landscape" },
        { type: "image", src: "assets/images/gallery/body-later/body-later-01.jpg", alt: "《如果我是 DJ 你会爱我吗》阿那亚戏剧节移动版本夜间现场", orientation: "landscape" },
        { type: "image", src: "assets/images/gallery/body-later/body-later-02.jpg", alt: "《如果我是 DJ 你会爱我吗》与现场观众互动", orientation: "landscape" },
        { type: "image", src: "assets/images/gallery/body-later/body-later-04.jpg", alt: "《如果我是 DJ 你会爱我吗》移动装置细节", orientation: "landscape" },
        { type: "video", src: "assets/video/archive/sound-web.mp4", poster: "assets/images/gallery/body-later/body-later-01.jpg", alt: "《如果我是 DJ 你会爱我吗》人脸按摩打击机影像", orientation: "landscape" },
      ],
      transition: "shutter",
      summaryZh:
        "按压人体背部的不同部位会触发不同声音。作品并置按摩、打碟与杀马特时期音乐，观察刻板印象如何进入身体经验，以及我们究竟是在感受对象，还是在重复既定判断。",
      summaryEn:
        "Pressing different parts of the back triggers different sounds. Massage, DJ performance and music associated with the Shamate era meet in one interface, exposing how stereotypes enter bodily experience and shape judgment.",
      stages: [
        {
          year: "2025",
          labelZh: "前期作品",
          labelEn: "Initial Work",
          title: "《人体按摩打碟机》",
          detailZh: "以身体按压作为声音触发方式，建立装置的交互机制与观念基础。",
          detailEn: "The first version uses pressure on the body to trigger sound, establishing the interaction and conceptual framework.",
        },
        {
          year: "2025",
          labelZh: "后续项目",
          labelEn: "Later Project",
          title: "《如果我是 DJ 你会爱我吗》· 阿那亚戏剧节",
          detailZh: "作品在候鸟300项目中转化为可移动、面向现场观众的项目版本。",
          detailEn: "For Migratory Birds 300, the work became a mobile project shaped around a live audience and festival setting.",
        },
      ],
      futureAssets: [],
    },
    {
      id: "shadow-puppet",
      order: 4,
      featured: true,
      titleZh: "桩影戏",
      titleEn: "Post Shadow Play",
      aliases: [],
      year: "2024",
      categoryZh: "数字投影",
      categoryEn: "Projection Mapping",
      roleZh: "个人作品",
      roleEn: "Personal Work",
      preview: {
        type: "video",
        src: "assets/video/post-shadow-play.mp4",
        poster: "assets/images/post-shadow-play.png",
        alt: "《桩影戏》在石刻表面的数字投影现场",
        orientation: "landscape",
      },
      gallery: [
        { type: "image", src: "assets/images/gallery/shadow-02.png", alt: "《桩影戏》数字投影现场图二", orientation: "landscape" },
        { type: "image", src: "assets/images/gallery/shadow-03.png", alt: "《桩影戏》数字投影现场图三", orientation: "landscape" },
        { type: "image", src: "assets/images/gallery/shadow-04.png", alt: "《桩影戏》数字投影现场图四", orientation: "landscape" },
      ],
      transition: "split",
      summaryZh:
        "作品走近雁塔拴马桩，让光、影与古老石刻在数字投影中重新相遇。现实的重量逐渐退场，图像将现场引向一个介于遗存、梦境与幻想之间的空间。",
      summaryEn:
        "Projection brings light and moving images to the stone hitching posts near the Wild Goose Pagoda. Their physical weight gives way to a space between historical remains, dreams and fantasy.",
      stages: [],
      futureAssets: [],
    },
    {
      id: "transcendence",
      order: 5,
      featured: true,
      titleZh: "脱敏",
      titleEn: "Desensitization",
      aliases: [],
      year: "2024",
      categoryZh: "数字投影",
      categoryEn: "Projection Mapping",
      roleZh: "团队作品",
      roleEn: "Collaborative Work",
      preview: {
        type: "video",
        src: "assets/video/desensitization-chongqing-latest.mp4",
        poster: "assets/images/transcendence.png",
        alt: "《脱敏》重庆光影艺术节影像",
        orientation: "landscape",
      },
      gallery: [
        { type: "image", src: "assets/images/gallery/transcendence-02.png", alt: "《脱敏》投影现场图二", orientation: "landscape" },
        { type: "image", src: "assets/images/gallery/transcendence-03.png", alt: "《脱敏》投影现场图三", orientation: "landscape" },
        { type: "image", src: "assets/images/gallery/transcendence-04.png", alt: "《脱敏》投影现场图四", orientation: "landscape" },
      ],
      transition: "diagonal",
      summaryZh:
        "数字媒介把个体行为与更广泛的信息系统相连。作品讨论人如何参与自己行为产生的结果，以及媒介怎样改变信息被接收、处理与反馈的方式。",
      summaryEn:
        "Digital media connects individual actions to a wider information system. The work considers how people participate in the consequences of their actions and how media changes the reception, processing and return of information.",
      stages: [],
      futureAssets: [],
    },
    {
      id: "weiqu-south",
      order: 6,
      featured: true,
      titleZh: "韦曲南",
      titleEn: "Weiqu South",
      aliases: [],
      year: "2024",
      categoryZh: "影像与数字表皮",
      categoryEn: "Moving Image / Media Facade",
      roleZh: "项目参与",
      roleEn: "Project Contributor",
      preview: {
        type: "video",
        src: "assets/video/weiqu-south-web.mp4",
        poster: "assets/images/weiqu-south.png",
        alt: "《韦曲南》城市数字表皮完整影像",
        orientation: "landscape",
      },
      gallery: [
        { type: "image", src: "assets/images/weiqu-south.png", alt: "《韦曲南》数字表皮视觉中的人物与城市结构", orientation: "portrait" },
        { type: "image", src: "assets/images/gallery/weiqu-02.jpg", alt: "《韦曲南》数字视觉图二", orientation: "portrait" },
        { type: "image", src: "assets/images/gallery/weiqu-03.jpg", alt: "《韦曲南》数字视觉图三", orientation: "portrait" },
        { type: "image", src: "assets/images/gallery/weiqu-04.jpg", alt: "《韦曲南》数字视觉图四", orientation: "portrait" },
      ],
      galleryLayout: "quad-video",
      transition: "iris",
      summaryZh:
        "现实生活与信息化生活彼此缠绕，却遵循不同的生态准则。作品观察人如何在现实与网络之间调整自己，并在两种身份和环境中维持暂时的平衡。",
      summaryEn:
        "Physical and networked life remain closely connected while following different rules. The work observes how a person adjusts between them and maintains a temporary balance across environments and identities.",
      stages: [],
      futureAssets: [],
    },
    {
      id: "today-ends-here",
      featured: false,
      titleZh: "今天就先到这里",
      titleEn: "Let's Stop Here for Today",
      year: "2023",
      categoryZh: "静态装置",
      categoryEn: "Static Installation",
      aliases: [],
      roleZh: "个人作品",
      roleEn: "Personal Work",
      materialsZh: "旧笔记本、二手书桌",
      materialsEn: "Used notebooks, second-hand desk",
      dimensions: "尺寸可变 / Variable dimensions",
      displayZh: "装置",
      displayEn: "Installation",
      preview: { type: "image", src: "assets/images/archive/今天就先到这里 图片1.jpg", alt: "《今天就先到这里》作品图一", orientation: "portrait" },
      gallery: [
        { type: "image", src: "assets/images/archive/今天就先到这里 图片2.jpg", alt: "《今天就先到这里》作品图二", orientation: "portrait" },
        { type: "image", src: "assets/images/archive/今天就先到这里 图片3.jpg", alt: "《今天就先到这里》作品图三", orientation: "portrait" },
      ],
      summaryZh: "作品始于二手市场中一本记录多年计划、心情与日常的旧笔记本。艺术家收集不同人的笔记本，并将二手书桌以不稳定的倾斜状态放置。作品不试图替原主人讲述人生，而是关注私人生活如何被留存在微小物件中，又在陌生人之间不断流转。",
      summaryEn: "The work began with an old notebook found at a second-hand market, filled with years of plans, emotions and daily records. Notebooks collected from different people are presented with a second-hand desk placed at an unstable angle. Rather than narrating the former owners' lives, the installation considers how private experience remains within small objects and continues to circulate among strangers.",
      stages: [],
    },
    {
      id: "forward",
      featured: false,
      titleZh: "前进！",
      titleEn: "Forward!",
      year: "2023",
      categoryZh: "雕塑",
      categoryEn: "Sculpture",
      aliases: [],
      roleZh: "个人作品",
      roleEn: "Personal Work",
      materialsZh: "陶土、金属喷漆",
      materialsEn: "Clay, metallic spray paint",
      preview: { type: "image", src: "assets/images/archive/图片一《前进》雕塑 92cmx7cmx43.5cm 2024年12月.jpg", alt: "《前进！》雕塑正面", orientation: "landscape" },
      gallery: [
        { type: "image", src: "assets/images/archive/图片二《前进》雕塑 92cmx7cmx43.5cm 2024年12月.jpg", alt: "《前进！》雕塑侧面", orientation: "portrait" },
        { type: "image", src: "assets/images/archive/图片三《前进》雕塑 92cmx7cmx43.5cm 2024年12月.jpg", alt: "《前进！》雕塑细节", orientation: "portrait" },
      ],
      galleryLayout: "forward-mixed",
      summaryZh: "作品源于对罗家寨城中村的实地考察。雕塑以两栋“握手楼”之间最窄的 25 厘米为尺度依据，塑造一个瘦削的人坐在孤舟上。狭窄小径如支流汇入城市的海洋，城中村与其中的个体也在融入大城市的过程中逐渐消失。",
      summaryEn: "The work grew from field research in Luojiazhai urban village. Its scale refers to the narrowest 25-centimetre gap between two so-called handshake buildings, while its form shows a gaunt figure seated in a solitary boat. The village's narrow paths become tributaries flowing into the larger sea of the city, where both place and individual gradually disappear through assimilation.",
      stages: [],
    },
    {
      id: "crowd",
      featured: false,
      titleZh: "人从众",
      titleEn: "Crowd",
      year: "2024",
      categoryZh: "影像装置",
      categoryEn: "Moving Image Installation",
      aliases: [],
      roleZh: "个人作品",
      roleEn: "Personal Work",
      duration: "03:56",
      preview: { type: "video", src: "assets/video/archive/crowd-web.mp4", alt: "《人从众》完整影像", orientation: "landscape" },
      gallery: [
        { type: "image", src: "assets/images/archive/crowd-01.jpg", alt: "《人从众》装置现场", orientation: "landscape" },
        { type: "image", src: "assets/images/archive/crowd-03.png", alt: "《人从众》作品图三", orientation: "landscape" },
        { type: "image", src: "assets/images/archive/crowd-04.png", alt: "《人从众》作品图四", orientation: "landscape" },
      ],
      summaryZh: "作品探讨人与人之间的关系，以及群体对个体不幸的漠视。当个人责任感在群体中逐渐弱化，旁观者效应便成为我们必须面对的问题。",
      summaryEn: "The work examines relationships between people and a group's indifference to individual misfortune. As personal responsibility weakens within the crowd, the bystander effect becomes a problem we must confront.",
      stages: [],
    },
    {
      id: "sun-also-rises",
      featured: false,
      titleZh: "太阳照常升起",
      titleEn: "The Sun Also Rises",
      year: "2024",
      categoryZh: "手绘影像",
      categoryEn: "Hand-drawn Moving Image",
      aliases: [],
      roleZh: "个人作品",
      roleEn: "Personal Work",
      duration: "00:15",
      preview: { type: "video", src: "assets/video/archive/sun-also-rises.mp4", poster: "assets/images/archive/sun-sequence-01.png", alt: "《太阳照常升起》完整手绘影像", orientation: "landscape" },
      gallery: [
        { type: "image", src: "assets/images/archive/sun-sequence-01.png", alt: "《太阳照常升起》时间画面一", orientation: "portrait" },
        { type: "image", src: "assets/images/archive/sun-sequence-02.png", alt: "《太阳照常升起》时间画面二", orientation: "portrait" },
        { type: "image", src: "assets/images/archive/sun-sequence-03.png", alt: "《太阳照常升起》时间画面三", orientation: "portrait" },
        { type: "image", src: "assets/images/archive/sun-sequence-04.png", alt: "《太阳照常升起》时间画面四", orientation: "portrait" },
      ],
      galleryLayout: "sequence-pairs",
      summaryZh: "这件手绘动画也是一次思想漫游：窗外从砖房、民房变成高楼大厦，再通向仍在不断搭建的未来。面对文明与暴力的冲突，我们会去向哪里，一切是否真的如故？最终太阳照常升起——如故吗？如故。",
      summaryEn: "This hand-drawn animation is also a wandering train of thought. Outside the window, brick houses give way to homes, towers and a future still under construction. Amid the conflict between violence and civilization, where are we going, and does everything truly remain the same? In the end, the sun rises as usual—but is it as usual? As usual.",
      stages: [],
    },
    {
      id: "sugar-radio",
      featured: false,
      titleZh: "SUGAR-RADI0",
      titleEn: "SUGAR-RADI0",
      year: "2024",
      categoryZh: "影像",
      categoryEn: "Moving Image",
      aliases: [],
      roleZh: "合作项目",
      roleEn: "Collaborative Project",
      preview: { type: "video", src: "assets/video/archive/sugar-radio-web.mp4", poster: "assets/images/archive/sugar-01.png", alt: "SUGAR-RADI0 完整影像", orientation: "landscape" },
      gallery: [
        { type: "image", src: "assets/images/archive/sugar-01.png", alt: "SUGAR-RADI0 影像画面一", orientation: "landscape" },
        { type: "image", src: "assets/images/archive/sugar-02.png", alt: "SUGAR-RADI0 影像画面二", orientation: "landscape" },
        { type: "image", src: "assets/images/archive/sugar-03.png", alt: "SUGAR-RADI0 影像画面三", orientation: "landscape" },
        { type: "image", src: "assets/images/archive/sugar-04.png", alt: "SUGAR-RADI0 影像画面四", orientation: "landscape" },
        { type: "image", src: "assets/images/archive/sugar-05.png", alt: "SUGAR-RADI0 影像画面五", orientation: "landscape" },
        { type: "image", src: "assets/images/archive/sugar-06.png", alt: "SUGAR-RADI0 影像画面六", orientation: "landscape" },
      ],
      summaryZh: "把糖果转化为可以演奏、也可以食用的乐器，让味觉、触觉与声音跨越媒介相遇，在趣味实验中尝试松动对乐器与感官经验的既定理解。",
      summaryEn: "Candy becomes an instrument that can be played and eaten, bringing taste, touch and sound together in a playful experiment that loosens fixed ideas of instruments and sensory experience.",
      stages: [],
    },
    {
      id: "bath",
      featured: false,
      imagesOnly: true,
      titleZh: "浴",
      titleEn: "Bath",
      year: "2024",
      categoryZh: "墙绘",
      categoryEn: "Mural",
      aliases: [],
      roleZh: "个人作品",
      roleEn: "Personal Work",
      preview: { type: "image", src: "assets/images/archive/bath-01.jpg", alt: "《浴》作品图一", orientation: "portrait" },
      gallery: [
        { type: "image", src: "assets/images/archive/bath-02.jpg", alt: "《浴》作品图二", orientation: "portrait" },
        { type: "image", src: "assets/images/archive/bath-03.jpg", alt: "《浴》作品图三", orientation: "portrait" },
      ],
      summaryZh: "作品说明待补充。",
      summaryEn: "Project text pending.",
      stages: [],
    },
    {
      id: "falling",
      featured: false,
      imagesOnly: true,
      titleZh: "坠",
      titleEn: "Falling",
      year: "2023",
      categoryZh: "绘画",
      categoryEn: "Painting",
      aliases: [],
      roleZh: "个人作品",
      roleEn: "Personal Work",
      preview: { type: "image", src: "assets/images/archive/falling-01.jpg", alt: "《坠》绘画作品", orientation: "landscape" },
      gallery: [],
      summaryZh: "作品说明与更多图片待补充。",
      summaryEn: "Project text and additional images pending.",
      stages: [],
    },
    {
      id: "blue-white-porcelain",
      featured: false,
      imagesOnly: true,
      titleZh: "青花瓷",
      titleEn: "Blue and White Porcelain",
      year: "2023",
      categoryZh: "绘画",
      categoryEn: "Painting",
      aliases: [],
      roleZh: "个人作品",
      roleEn: "Personal Work",
      preview: { type: "image", src: "assets/images/archive/blue-white-01.jpg", alt: "《青花瓷》绘画作品", orientation: "landscape" },
      gallery: [],
      summaryZh: "作品说明与更多图片待补充。",
      summaryEn: "Project text and additional images pending.",
      stages: [],
    },
    {
      id: "big-bite",
      featured: false,
      imagesOnly: true,
      galleryLayout: "pairs",
      titleZh: "大吃一口",
      titleEn: "A Big Bite",
      year: "2023",
      categoryZh: "综合绘画",
      categoryEn: "Mixed-media Painting",
      aliases: [],
      roleZh: "个人作品",
      roleEn: "Personal Work",
      preview: { type: "image", src: "assets/images/archive/big-bite-01.jpg", alt: "《大吃一口》作品图一", orientation: "square" },
      gallery: [
        { type: "image", src: "assets/images/archive/big-bite-02.jpg", alt: "《大吃一口》作品图二", orientation: "square" },
        { type: "image", src: "assets/images/archive/big-bite-03.jpg", alt: "《大吃一口》作品图三", orientation: "square" },
        { type: "image", src: "assets/images/archive/big-bite-04.jpg", alt: "《大吃一口》作品图四", orientation: "square" },
        { type: "image", src: "assets/images/archive/big-bite-05.jpg", alt: "《大吃一口》作品图五", orientation: "square" },
        { type: "image", src: "assets/images/archive/big-bite-06.jpg", alt: "《大吃一口》作品图六", orientation: "square" },
        { type: "image", src: "assets/images/archive/big-bite-07.jpg", alt: "《大吃一口》作品图七", orientation: "square" },
        { type: "image", src: "assets/images/archive/big-bite-08.jpg", alt: "《大吃一口》作品图八", orientation: "square" },
        { type: "image", src: "assets/images/archive/big-bite-09.jpg", alt: "《大吃一口》作品图九", orientation: "square" },
        { type: "image", src: "assets/images/archive/big-bite-10.jpg", alt: "《大吃一口》作品图十", orientation: "square" },
      ],
      summaryZh: "作品说明待补充。",
      summaryEn: "Project text pending.",
      stages: [],
    },
    {
      id: "towards-series",
      featured: false,
      imagesOnly: true,
      titleZh: "向 · 系列",
      titleEn: "Towards · Series",
      year: "2024",
      categoryZh: "写生水粉",
      categoryEn: "Gouache Studies",
      aliases: [],
      roleZh: "个人作品",
      roleEn: "Personal Work",
      preview: { type: "image", src: "assets/images/archive/towards-01.jpg", alt: "《向·系列》写生作品一", orientation: "portrait" },
      gallery: [
        { type: "image", src: "assets/images/archive/towards-02.jpg", alt: "《向·系列》写生作品二", orientation: "portrait" },
        { type: "image", src: "assets/images/archive/towards-03.jpg", alt: "《向·系列》写生作品三", orientation: "portrait" },
      ],
      summaryZh: "作品说明待补充。",
      summaryEn: "Project text pending.",
      stages: [],
    },
    {
      id: "fuzhou-airport",
      featured: false,
      imagesOnly: true,
      titleZh: "福州机场 · 福蛇翔瑞迎春艺术节",
      titleEn: "Fuzhou Airport Spring Festival",
      year: "2024",
      categoryZh: "展台与视觉设计",
      categoryEn: "Spatial / Visual Design",
      aliases: [],
      roleZh: "项目参与",
      roleEn: "Project Contributor",
      preview: { type: "image", src: "assets/images/archive/fuzhou-01.png", alt: "福州机场春节项目角色视觉", orientation: "landscape" },
      gallery: [
        { type: "image", src: "assets/images/archive/fuzhou-02.jpg", alt: "福州机场春节项目现场二", orientation: "landscape" },
        { type: "image", src: "assets/images/archive/fuzhou-03.jpg", alt: "福州机场春节项目现场三", orientation: "landscape" },
        { type: "image", src: "assets/images/archive/fuzhou-04.jpg", alt: "福州机场春节项目现场四", orientation: "landscape" },
        { type: "image", src: "assets/images/archive/fuzhou-05.jpg", alt: "福州机场春节项目现场五", orientation: "landscape" },
        { type: "image", src: "assets/images/archive/fuzhou-06.png", alt: "福州机场春节项目设计图", orientation: "landscape" },
      ],
      summaryZh: "福州机场福蛇翔瑞迎春艺术节的展台与视觉设计项目。更完整的职责说明与项目文字待补充。",
      summaryEn: "Spatial and visual design for the Fuzhou Airport Spring Festival project. A fuller role description and project text are pending.",
      stages: [],
    },
    {
      id: "shanghai-hualong",
      featured: false,
      imagesOnly: true,
      titleZh: "上海黄龙国际大厅美陈",
      titleEn: "Shanghai Hualong Lobby Installation",
      year: "2024",
      categoryZh: "美陈与建模",
      categoryEn: "Spatial Display / 3D",
      aliases: [],
      roleZh: "项目参与",
      roleEn: "Project Contributor",
      preview: { type: "image", src: "assets/images/archive/shanghai-01.png", alt: "上海黄龙国际大厅美陈现场", orientation: "portrait" },
      gallery: [
        { type: "image", src: "assets/images/archive/shanghai-02.jpg", alt: "上海黄龙国际大厅美陈现场二", orientation: "portrait" },
        { type: "image", src: "assets/images/archive/shanghai-03.png", alt: "上海黄龙国际大厅美陈现场三", orientation: "portrait" },
        { type: "image", src: "assets/images/archive/shanghai-04.png", alt: "上海黄龙国际大厅美陈设计图", orientation: "landscape" },
        { type: "image", src: "assets/images/archive/shanghai-05.png", alt: "上海黄龙国际大厅美陈建模图", orientation: "landscape" },
        { type: "image", src: "assets/images/archive/shanghai-06.png", alt: "上海黄龙国际大厅美陈建模图二", orientation: "landscape" },
      ],
      summaryZh: "上海黄龙国际大厅的空间美陈与建模项目。更完整的职责说明与项目文字待补充。",
      summaryEn: "Spatial display and 3D modeling for the Shanghai Hualong lobby. A fuller role description and project text are pending.",
      stages: [],
    },
  ],
  archiveGroups: [
    {
      titleZh: "装置",
      titleEn: "Installation",
      workIds: ["work-introduction", "revelation", "body-massage-dj", "today-ends-here", "forward"],
    },
    {
      titleZh: "观念与绘画",
      titleEn: "Concept / Painting",
      workIds: ["bath", "falling", "blue-white-porcelain", "big-bite", "towards-series"],
    },
    {
      titleZh: "投影与影像",
      titleEn: "Projection / Moving Image",
      workIds: ["shadow-puppet", "transcendence", "weiqu-south", "crowd", "sun-also-rises", "sugar-radio"],
    },
    {
      titleZh: "公共项目",
      titleEn: "Public Projects",
      projectLinks: [
        {
          workId: "work-introduction",
          titleZh: "林茨电子艺术节 · The Critic",
          titleEn: "Ars Electronica · The Critic",
          categoryZh: "展览项目",
          year: "2026",
        },
        {
          workId: "body-massage-dj",
          titleZh: "阿那亚戏剧节 ·《如果我是 DJ 你会爱我吗》",
          titleEn: "Aranya Theater Festival · If I Were a DJ, Would You Love Me?",
          categoryZh: "候鸟 300 项目",
          year: "2025",
        },
      ],
      workIds: ["fuzhou-airport", "shanghai-hualong"],
    },
  ],
};
